fileVersion: 3

GlobalyEnable: true
#Checks settings related to difficulty in selected world. If you leave WorldName blank it will choose first world automaticaly.
WorldName:
#example: WorldName: "my_world"
AffectedWorlds: [world, world_nether, world_the_end]
peaceful:
  CheckDelay: 86400
  StartDelay: 86400
easy:
  CheckDelay: 10
  StartDelay: 20
normal:
  CheckDelay: 8
  StartDelay: 14
hard:
  CheckDelay: 6
  StartDelay: 8

#Chat related functions
NumberOfChecksPerWarningMessage: 5
DebugMode: false
DebugGlassBlocks: false

CanChangeWeather: true
BroadcastForecast: true

ErrorReporting: true
ErrorReportingName: Unknown

Language: eng